### PR TITLE
Reposition hidden files only if background image is available

### PR DESCRIPTION
**Pull request by kaloyan-raev**
Resolves the issue described by @hermwong in https://github.com/andreyvit/yoursway-create-dmg/pull/35

### CODE REVIEW

**Comment by andreyvit** [comment]
Thanks for the fix!

**Comment by andreyvit** [comment]
As per my new policy:

> Starting in January 2015, everyone who gets a pull request merged gets commit access to the repository.

you're now a committer. Feel free to do anything you want with this repo. :-)

**Comment by kaloyan-raev** [comment]
@andreyvit Thank you for the privilege! Many thanks also for the great project you've started. It helped lots of people making their way through DMG packaging.

**Comment by andreyvit** [comment]
@kaloyan-raev One of several useful pieces from a failed startup I tried to bootstrap many years ago :-)

**Comment by hermwong** [comment]
Hi, I've been testing this pull request. I'm still seeing the hidden files within the window of the disk image even when using a background image.

screen shot provided:

screen shot 2015-02-05 at 3 59 24 pm

here is the list parameters that I'm using:

```
#! /bin/bash 
test -f ../../../installers/osx/PhoneGapDesktop.dmg && rm ../../../installers/osx/PhoneGapDesktop.dmg 

./create-dmg \
--volname "PhoneGap Desktop Installer" \
--background "bg-512-320.png" \
--window-size 512 320 \
--icon-size 64 \
--icon PhoneGap.app 125 160 \
--hide-extension PhoneGap.app \
--app-drop-link 385 160 \
--eula license.txt \
../../../installers/osx/PhoneGapDesktop.dmg \
../../../build/PhoneGap/OSX
```

**Pull request merged**
